// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt_zaliczeniowy.Data;

namespace Projekt_zaliczeniowy.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220607200852_test")]
    partial class test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Projekt_zaliczeniowy.Models_api+Dane_pomiarowe", b =>
                {
                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.HasKey("DateTime");

                    b.ToTable("history_Data_Measurements");
                });

            modelBuilder.Entity("Projekt_zaliczeniowy.Models_api+Values", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Dane_pomiaroweDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Dane_pomiaroweDateTime");

                    b.ToTable("Values");
                });

            modelBuilder.Entity("Projekt_zaliczeniowy.Models_api+Values", b =>
                {
                    b.HasOne("Projekt_zaliczeniowy.Models_api+Dane_pomiarowe", null)
                        .WithMany("IValues")
                        .HasForeignKey("Dane_pomiaroweDateTime");
                });

            modelBuilder.Entity("Projekt_zaliczeniowy.Models_api+Dane_pomiarowe", b =>
                {
                    b.Navigation("IValues");
                });
#pragma warning restore 612, 618
        }
    }
}
